server:
  port: 80

#logging:
#  level:
#    org.springframework: DEBUG

spring:
  messages:
    basename: messages
  security:
    user:
      name: username
      password: password

jpa:
  show-sql: true
h2:
  console:
    enable: true

management:
  endpoints:
    web:
      exposure:
        include:"*"