server:
  port: 80


h2:
  console:
    enable: true

#logging:
#  level:
#    org.springframework: DEBUG

spring:
  datasource:
    url: jdbc:h2:mem:testmem # 메모리 db
#    url: jdbc:h2:~/test     # 로컬 db
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  messages:
    basename: messages
  security:
    user:
      name: username
      password: password



management:
  endpoints:
    web:
      exposure:
        include:"*"